name: Rust

on:
  workflow_dispatch:
    

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build release
      run: cargo build --release --verbose
    - name: Get tag from Cargo.toml
      run: cat Cargo.toml | sed -n '/version/ { s/ //g; s/version/tagName/; p; }' >> $GITHUB_ENV
    - name: Check output of step above
      run: echo "${{ env.tagName }}"
    - name: GH Release
      uses: softprops/action-gh-release@v0.1.14
      with:
          files: target/release/zint
          tag_name: "${{ env.tagName }}"
      
